# Generated by Django 4.0.4 on 2022-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Zip', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
    ]
